@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Interface UserPrefsStorage <<Interface>>
Class JsonUserPrefsStorage
}

Interface Storage <<Interface>>
Class StorageManager

package "GuestBook Storage" #F4F6F6{
note "Also exists for \n Vendor \n (VendorBookStorage) \n and Archive \n (ArchiveBookStorage)" as N
Interface GuestBookStorage <<Interface>>
Class JsonGuestBookStorage
Class JsonSerializableGuestBookStorage
Class JsonAdaptedGuest
Class JsonAdaptedTag
Class JsonAdaptedChargeable
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1"GuestBookStorage

Storage -left-|> UserPrefsStorage
Storage -right-|>GuestBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonGuestBookStorage .up.|>GuestBookStorage
JsonGuestBookStorage ..> JsonSerializableGuestBookStorage
JsonSerializableGuestBookStorage --> "*" JsonAdaptedGuest
JsonAdaptedGuest --> "*" JsonAdaptedTag
JsonAdaptedGuest --> "*" JsonAdaptedChargeable

@enduml
